language: "python"

python:
  - "3.6"

env:
  - "PIPENV_IGNORE_VIRTUALENVS=1"

before_script:
  - "pip install --no-cache-dir poetry"
  - "poetry install"

script:
  - "poetry run flake8 ."

notifications:
  email:
    on_success: "never"
    on_failure: "always"
